### PR TITLE
Get-SqlInstance should be an array even if it returns only one element

### LINKED ISSUE #340: checkdb test reports passed and failed as same
Run Invoke-DbcCheck -SqlInstance serverName -check LastGoodCheckDb

I have 11 databases that do not have LastGoodCheckDb.

Results:
Tests Passed: 11, Failed: 11, Skipped: 0, Pending: 0, Inconclusive: 0 

Expected Results : 
Tests Passed:0, Failed: 11

### PR DESCRIPTION
**Pull request by michalporeba**
I've add @ before all (Get-SqlInstance).ForEach
It resolves #340, #327

### CODE REVIEW

**Comment by potatoqualitee** [comment]
Darn, I was hoping to avoid having to do this on every test with this:

https://github.com/sqlcollaborative/dbachecks/blob/master/internal/functions/Get-SqlInstance.ps1#L11

Any idea why this didn't work? We can update the template and merge this PR as well, but was looking for a sleeker solution.

**Comment by SQLDBAWithABeard** [comment]
Could we specify the outputtype as an array? Would that do it?

**Comment by potatoqualitee** [comment]
ohhh! that sounds like a nice potential. will look into it

**Comment by SQLDBAWithABeard** [comment]
I am worried about leaving this open too long as the merge will become very conflicted.

**Comment by potatoqualitee** [comment]
It's been conflicted for a while, unfortunately. I would actually like to rewrite Get-Sqlinstance and Get-ComputerName real quick instead. Let's try that, brb

**Comment by potatoqualitee** [comment]
So sorry, @michalporeba - I was trying to figure this out w/o having to modify the easy-ish to read template. If #365 doesn't work, I'll update all of these myself. Thank you for your work!

**Pull request closed without merging**
