### PR TITLE
update with slimmer get-database

### PR DESCRIPTION
**Pull request by potatoqualitee**
don't merge yet, just want to make this more visible for testing

### CODE REVIEW

**Comment by SQLDBAWithABeard** [comment]
OK, shall we create a feature branch for this and work in that until we are happy?

**Comment by potatoqualitee** [comment]
I ping @michalporeba asking if he could test it. If it's much faster and works as expected, then we can merge. If not, we can create a feature branch.

**Comment by potatoqualitee** [comment]
ill resolve the conflicts once we decide it's 👍  anyone who can test that this is a solid solution is welcomed

**Comment by michalporeba** [comment]
I have tested this approach and while it is a significant improvement to what it was it is still considerably slower than my approach. On a single, simple test like auto shrink the longest I have ran the original method was just over 9 hours and I got no results. This change make such tests run around 15-16 minutes in my test environment. My method (#316) gives results in 14-15 seconds. 

So while I think it is very welcome improvement, which will make it possible for me to use dba tools I think I'd like to carry on with my approach to faster testing. I know it is significantly more work, but it is 60 times faster too. 

I'd suggest not to merge this change, and instead add it to the dbatools. It might be that I will need to use it in some checks, but hopefully by then it will be already in dbatools?

**Comment by potatoqualitee** [comment]
works for me! thank you, @michalporeba . I will close this request

**Comment by potatoqualitee** [comment]
dbatools will be modified as well, but needs a bit more care and announcements

**Pull request closed without merging**
