### PR TITLE
Add back Credential and SqlCredential Support

### PR DESCRIPTION
**Pull request by potatoqualitee**

### CODE REVIEW

**Comment by potatoqualitee** [comment]
to test, i added a sqlcred with bad password and showed it will fail (i also tested where the user exists and it passes)

image

**Comment by wsmelton** [comment]
Curious why all the extra output on running "Agent" test shows if you only specified backup checks to run?

As well, is there no mechanism in place to say if it can't access the instance stop trying to run the test against it or using the cred?

**Comment by SQLDBAWithABeard** [comment]
unfortunately not - It could be done though

**Comment by potatoqualitee** [comment]
> Curious why all the extra output on running "Agent" test shows if you only specified backup checks to run?

That's just the way Pester does it. It runs each ps1 looking for the appropriate tags.

> As well, is there no mechanism in place to say if it can't access the instance stop trying to run the test against it or using the cred?

We'd have to test the output likely. I'm not a fan of the idea, though don't have the brain power today to put my finger on why.

**Pull request merged**
