### PR TITLE
ok this was the 'bug'

### PR DESCRIPTION
**Pull request by SQLDBAWithABeard**
and now its fixed ;-)
https://twitter.com/sqldbawithbeard/status/1029822270427017217

### CODE REVIEW

**Comment by potatoqualitee** [comment]
wait, what was the difference?

**Comment by SQLDBAWithABeard** [comment]
The curly braces in the Database.Tests

It went

Describe {

Describe {}
Describe {}
Describe {}
Describe {}

}

Grrrr but it seems different versions of pester treat that differently

**Comment by SQLDBAWithABeard** [comment]
So completely my fault but weird all the same

**Comment by potatoqualitee** [comment]
ah haaa! yeah totally weird

**Comment by SQLDBAWithABeard** [comment]
I'm holding off on 4.4.0 because I had it fail on tags in a custom repo that I am using at a shop and I do not want to break that one

**Pull request merged**
