### PR TITLE
Fix space between -skip and test; move Get-DbaDump call inside of the It

### PR DESCRIPTION
**Pull request by ashdar**
# A New PR

THANK YOU - We love to get PR's and really appreciate your time and help to improve this module

## Accepting a PR

Before we accept the PR - please confirm that you have run the tests locally to avoid our automated build and release process failing. You can see how to do that in our wiki

https://github.com/sqlcollaborative/dbachecks/wiki 

## Please confirm you have 0 failing Pester Tests

[X] There are 0 failing Pester tests

## Changes this PR brings

#685

### CODE REVIEW

**Comment by ashdar** [comment]
I have done the bare minimum here, I think, to get this working. 
Basically, I am just changing a space to a colon:
I also had to move the Get-DbaDump also or the It still gives a serious-fatal-looking red error because Get-DbaDump has it's own method of detecting servers that are "too old". 

The way it works now, you get a simple skip message:

  Describing SQL Memory Dumps
    Context Checking that dumps on SDE01 do not exceed 1 for SDE01
      [!] dump count of  is less than or equal to the 1 dumps on SDE01, is skipped 0ms
Tests completed in 412ms
Tests Passed: 0, Failed: 0, Skipped: 1, Pending: 0, Inconclusive: 0

That message doesn't describe why the test is skipped very well. I considered using Set-ItResult, but I couldn't find any other use if Set-ItResult in this project and I thought maybe my version of pester is too modern (and I'd be changing the required version for a dependency) or there is some other reason to avoid Set-ItResult. So I kept it simple.

HTH,
-d

**Comment by SQLDBAWithABeard** [comment]
You are a diamond and a scholar. Thank you for this.

I am going to close this PR only because I fixed the : for space direct to master last night.  

https://github.com/sqlcollaborative/dbachecks/commit/310f02ee5d5c5e74563bf32b86737afeff369332 

I had to do it quickly as I was due in a meeting and wanted it sorted quickly.

I will add the moving of the dbadump to dev, ready for the next release.

I am not averse to updating requirement to 4.5 (?) I think for Set-ItResult

I am also considering using the Assert module to improve the layout of the failed test results.

I would be interested in your thoughts and thank you very much for your contributions

**Comment by ashdar** [comment]
I've used Set-ItResult for my own stuff; I like it because you can explain things a bit better without relying on a bunch of comments in a Tests file that you would have to go find and read.

I am gun shy with adding any sort of new dependency or a dependency on a 'recenter' version of something.  I've run into snafus with version dependencies and other things/projects where I wanted to update "just that one thing" and gotten surprised. Pester 4.7.1 should have Set-ItResult already, so it's just a question of using it now. 

I haven't used the Asserts module, though I have watched presentations about it. IIRC.

**Comment by SQLDBAWithABeard** [comment]
The only reason I consider the Assert module is that @nohwnd wrote it. I need to play with Set-ItResult a bit more. I would like to improve the output

**Pull request closed without merging**
