### PR TITLE
The Sea of Green

### PR DESCRIPTION
**Pull request by michalporeba**
The check files are growing in size, and with time will grow in number as well (I have two in mind already). The size of Database.Tests.ps1 makes it harder and harder to digest, and to work with, while the number of files will produce the see of green, even if we want to run just one test. 

Here is my first attempt on limiting it. If specific list of tags is provided, only the files containing those tags will be executed by Invoke-Pester. If `-Script`  or `-AllChecks` parameters are used, the behaviour is at is was. 

Have a look and please let me know what you think.

image

### CODE REVIEW

**Comment by potatoqualitee** [comment]
rad!! another thing i wanted to do but couldnt figure out. thanks, michal!

**Comment by michalporeba** [comment]
I think it is not quite there yet. At the moment each of the files is executed separately. It might be a problem. 

image

It produces to report two files too. Let me see if I can make it better.

**Comment by michalporeba** [comment]
image

Does this look better?

**Comment by michalporeba** [comment]
not only the output looks cleaner, the code is neater too

**Pull request merged**
