### PR TITLE
updated for faster/more robust module versions

### PR DESCRIPTION
**Pull request by potatoqualitee**

### CODE REVIEW

**Comment by potatoqualitee** [comment]
beard, plz merge! not sure how your process works. ill get it one day 😂

**Comment by SQLDBAWithABeard** [comment]
Apologies, I crashed yesterday.

**Comment by SQLDBAWithABeard** [comment]
Had to revert @potatoqualitee - Error with PSFramework @FriedrichWeinmann  
ParameterBindingException: A parameter cannot be found that matches parameter name 'Depth'.
        at Write-Config, <No file>: line 104
        at Register-PSFConfig<Process>, <No file>: line 181
        at Set-DbcConfig<Process>, <No file>: line 73
        at Import-DbcConfig<Process>, <No file>: line 53

**Comment by FriedrichWeinmann** [comment]
Heya Rob, thank you for including me on this 👍 .
Found the issue and solved it, update to v0.9.13.35 solves this.
Release is currently building, should be available any moment.

**Pull request merged**
