### PR TITLE
Force array from Get-SqlInstance

### PR DESCRIPTION
**Pull request by potatoqualitee**
This should work as seen in the screenshot below

### CODE REVIEW

**Comment by potatoqualitee** [comment]
image

Gonna try on v4

**Comment by potatoqualitee** [comment]
Works in 4 as well /cc @michalporeba 

image

**Comment by potatoqualitee** [comment]
whaaaat! sweet

**Comment by michalporeba** [comment]
I agree, that is much cleaner solution.

**Pull request merged**
