### PR TITLE
dbachecks uses dbatools 1.0 commands

### PR DESCRIPTION
**Pull request by shaneis**
# A New PR

THANK YOU - We love to get PR's and really appreciate your time and help to improve this module

## Accepting a PR

Before we accept the PR - please confirm that you have run the tests locally to avoid our automated build and release process failing. You can see how to do that in our wiki

https://github.com/sqlcollaborative/dbachecks/wiki 

## Please confirm you have 0 failing Pester Tests

[] There are 0 failing Pester tests

## Changes this PR brings

Please add below the changes that this PR covers. It doesnt need an essay just the bullet points :-)

* Ran Invoke-DbatoolsRenameHelper on dbachecks module
Addresses #624

### CODE REVIEW

**Comment by potatoqualitee** [comment]
The required version also needs to be upped. Will submit a PR

**Comment by SQLDBAWithABeard** [comment]
Thank you, Its ok, I am updating this morning for Core so I will add it in :-)

**Comment by potatoqualitee** [comment]
oh good, k!

**Comment by potatoqualitee** [comment]
please require 1.0.11 - it's the latest and has some bug fixes 👍

**Pull request merged**
